# Network
bind 0.0.0.0
protected-mode no
port 6379

# General
daemonize no
supervised no
loglevel notice

# Persistence
appendonly yes
appendfilename "appendonly.aof"
appendfsync everysec

# Memory
maxmemory 256mb
maxmemory-policy allkeys-lru

# Replication
replica-read-only yes

# Security
# requirepass clinica_redis_password_2024